const express=require("express")
const router=express.Router()
const userDataController=require("../controller/userDataControll")
const cartControll=require("../controller/cartController")
const pageController=require("../controller/userControll")
const wishlistController=require("../controller/wishlistControl")
const path=require("path")
const userLogout=require("../controller/commoncontrol")
const paymentController=require("../controller/paymentControll")
const couponController=require("../controller/couponController")
router.use(express.static(path.join(__dirname,"../public/clint")))


router.get("/login",userDataController.getLoginpage)
.get("/logout",userLogout.logout)
.post("/login",userDataController.postLogin)
.get("/signup",userDataController.getsignupage)
.post("/signup",userDataController.postSignup)
.get("/otpvalidation",userDataController.getSignupOtp)
.post("/otpvalidation",userDataController.postSignupOtp)
.post('/resendotp', userDataController.resendOtp)
.post("/forgot-password", userDataController.forgotPassword)
.post("/forgot-otp",userDataController.forgotOtp)
.post("/forgot-resend-otp",userDataController.forgotResendOtp)
.post("/password-reset",userDataController.changePassword)
.get("/index",pageController.getindex)
.get("/productdetail/:id",pageController.getProductDetail)
.post("/productreview",pageController.postProductReview)
.get("/usergrid",pageController.getGridView)
.get("/wishlist",wishlistController.getWishlist)
.post("/wishlist",wishlistController.postWishlist)
.get("/checkout",paymentController.getCheckOutPage)
.post("/address",userDataController.postUserAddress)
.get("/orders",pageController.getOrders)
.post("/coupondiscount",couponController.discountProcess)
.post("/removecoupon",couponController.removeDiscountCoupon)
.get("/myaccount",pageController.getMyAccount)
.get("/orderdetails/:id",pageController.getOrderDetails)

//cart
router.get("/cart",cartControll.getCartPage)
.post("/cart",cartControll.postCartPage)
.post("/update-cart",cartControll.updateCartQuantity)
.delete("/delete-cart",cartControll.deleteCart)
.post("/place-order",paymentController.postCheckOut)
.get("/success",paymentController.orderSuccess)
.get("/cartqty",pageController.getProductDetail)
module.exports=router